model:
  base_learning_rate: 3e-05
  target: ldm.models.diffusion.control.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    log_every_t: 200
    timesteps: 1000
    image_size: 64
    channels: 4
    u_cond_percent: 0.2
    scale_factor: 0.18215
    use_ema: False

    control_stage_config:
      target: ldm.models.diffusion.control.ControlNet
      params:
        use_checkpoint: True
        in_channels: 9
        hint_channels: 6
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        transformer_depth: 1
        context_dim: 768

    unet_config:
      target: ldm.models.diffusion.control.ControlledUnetModel
      params:
        image_size: 32 # unused
        in_channels: 9
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        add_conv_in_front_of_unet: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder

data:
  target: test.DataModuleFromConfig
  params:
      batch_size: 1
      wrap: False
      test:
          target: ldm.data.image_vitonhd.OpenImageDataset
          params:
              state: test
              dataset_dir: datasets/vitonhd
              type: unpaired

lightning:
  trainer:
    num_nodes: 1
    profiler: "simple"
    accelerator: 'ddp'
    gpus: "0,1"